require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AthletesController do

  # This should return the minimal set of attributes required to create a valid
  # Athlete. As you add validations to Athlete, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AthletesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all athletes as @athletes" do
      athlete = Athlete.create! valid_attributes
      get :index, {}, valid_session
      assigns(:athletes).should eq([athlete])
    end
  end

  describe "GET show" do
    it "assigns the requested athlete as @athlete" do
      athlete = Athlete.create! valid_attributes
      get :show, {:id => athlete.to_param}, valid_session
      assigns(:athlete).should eq(athlete)
    end
  end

  describe "GET new" do
    it "assigns a new athlete as @athlete" do
      get :new, {}, valid_session
      assigns(:athlete).should be_a_new(Athlete)
    end
  end

  describe "GET edit" do
    it "assigns the requested athlete as @athlete" do
      athlete = Athlete.create! valid_attributes
      get :edit, {:id => athlete.to_param}, valid_session
      assigns(:athlete).should eq(athlete)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Athlete" do
        expect {
          post :create, {:athlete => valid_attributes}, valid_session
        }.to change(Athlete, :count).by(1)
      end

      it "assigns a newly created athlete as @athlete" do
        post :create, {:athlete => valid_attributes}, valid_session
        assigns(:athlete).should be_a(Athlete)
        assigns(:athlete).should be_persisted
      end

      it "redirects to the created athlete" do
        post :create, {:athlete => valid_attributes}, valid_session
        response.should redirect_to(Athlete.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved athlete as @athlete" do
        # Trigger the behavior that occurs when invalid params are submitted
        Athlete.any_instance.stub(:save).and_return(false)
        post :create, {:athlete => {}}, valid_session
        assigns(:athlete).should be_a_new(Athlete)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Athlete.any_instance.stub(:save).and_return(false)
        post :create, {:athlete => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested athlete" do
        athlete = Athlete.create! valid_attributes
        # Assuming there are no other athletes in the database, this
        # specifies that the Athlete created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Athlete.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => athlete.to_param, :athlete => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested athlete as @athlete" do
        athlete = Athlete.create! valid_attributes
        put :update, {:id => athlete.to_param, :athlete => valid_attributes}, valid_session
        assigns(:athlete).should eq(athlete)
      end

      it "redirects to the athlete" do
        athlete = Athlete.create! valid_attributes
        put :update, {:id => athlete.to_param, :athlete => valid_attributes}, valid_session
        response.should redirect_to(athlete)
      end
    end

    describe "with invalid params" do
      it "assigns the athlete as @athlete" do
        athlete = Athlete.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Athlete.any_instance.stub(:save).and_return(false)
        put :update, {:id => athlete.to_param, :athlete => {}}, valid_session
        assigns(:athlete).should eq(athlete)
      end

      it "re-renders the 'edit' template" do
        athlete = Athlete.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Athlete.any_instance.stub(:save).and_return(false)
        put :update, {:id => athlete.to_param, :athlete => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested athlete" do
      athlete = Athlete.create! valid_attributes
      expect {
        delete :destroy, {:id => athlete.to_param}, valid_session
      }.to change(Athlete, :count).by(-1)
    end

    it "redirects to the athletes list" do
      athlete = Athlete.create! valid_attributes
      delete :destroy, {:id => athlete.to_param}, valid_session
      response.should redirect_to(athletes_url)
    end
  end

end
