require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExerciseSetsController do

  # This should return the minimal set of attributes required to create a valid
  # ExerciseSet. As you add validations to ExerciseSet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExerciseSetsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all exercise_sets as @exercise_sets" do
      exercise_set = ExerciseSet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:exercise_sets).should eq([exercise_set])
    end
  end

  describe "GET show" do
    it "assigns the requested exercise_set as @exercise_set" do
      exercise_set = ExerciseSet.create! valid_attributes
      get :show, {:id => exercise_set.to_param}, valid_session
      assigns(:exercise_set).should eq(exercise_set)
    end
  end

  describe "GET new" do
    it "assigns a new exercise_set as @exercise_set" do
      get :new, {}, valid_session
      assigns(:exercise_set).should be_a_new(ExerciseSet)
    end
  end

  describe "GET edit" do
    it "assigns the requested exercise_set as @exercise_set" do
      exercise_set = ExerciseSet.create! valid_attributes
      get :edit, {:id => exercise_set.to_param}, valid_session
      assigns(:exercise_set).should eq(exercise_set)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExerciseSet" do
        expect {
          post :create, {:exercise_set => valid_attributes}, valid_session
        }.to change(ExerciseSet, :count).by(1)
      end

      it "assigns a newly created exercise_set as @exercise_set" do
        post :create, {:exercise_set => valid_attributes}, valid_session
        assigns(:exercise_set).should be_a(ExerciseSet)
        assigns(:exercise_set).should be_persisted
      end

      it "redirects to the created exercise_set" do
        post :create, {:exercise_set => valid_attributes}, valid_session
        response.should redirect_to(ExerciseSet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exercise_set as @exercise_set" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseSet.any_instance.stub(:save).and_return(false)
        post :create, {:exercise_set => {}}, valid_session
        assigns(:exercise_set).should be_a_new(ExerciseSet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseSet.any_instance.stub(:save).and_return(false)
        post :create, {:exercise_set => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exercise_set" do
        exercise_set = ExerciseSet.create! valid_attributes
        # Assuming there are no other exercise_sets in the database, this
        # specifies that the ExerciseSet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExerciseSet.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => exercise_set.to_param, :exercise_set => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested exercise_set as @exercise_set" do
        exercise_set = ExerciseSet.create! valid_attributes
        put :update, {:id => exercise_set.to_param, :exercise_set => valid_attributes}, valid_session
        assigns(:exercise_set).should eq(exercise_set)
      end

      it "redirects to the exercise_set" do
        exercise_set = ExerciseSet.create! valid_attributes
        put :update, {:id => exercise_set.to_param, :exercise_set => valid_attributes}, valid_session
        response.should redirect_to(exercise_set)
      end
    end

    describe "with invalid params" do
      it "assigns the exercise_set as @exercise_set" do
        exercise_set = ExerciseSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => exercise_set.to_param, :exercise_set => {}}, valid_session
        assigns(:exercise_set).should eq(exercise_set)
      end

      it "re-renders the 'edit' template" do
        exercise_set = ExerciseSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => exercise_set.to_param, :exercise_set => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exercise_set" do
      exercise_set = ExerciseSet.create! valid_attributes
      expect {
        delete :destroy, {:id => exercise_set.to_param}, valid_session
      }.to change(ExerciseSet, :count).by(-1)
    end

    it "redirects to the exercise_sets list" do
      exercise_set = ExerciseSet.create! valid_attributes
      delete :destroy, {:id => exercise_set.to_param}, valid_session
      response.should redirect_to(exercise_sets_url)
    end
  end

end
